# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c9ae029b4adba96ea4438f8bace3a3edf5d1f70c6ec5dac4ac3db4b2510734f87f6506dc08301920d85b777e8a40755512d86f088ac7e001ded0eb09c56ab12

test:
  secret_key_base: 3eee20bf9a82a6634bb587f21f55a321b95f019e1039c5ea8d86f4dfc28da6565991a463cc35811bce870aacd4cf596e95ae0cf0c37f1bea84b6aea34566c25e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
